name: Build on Pull Request

# Trigger the workflow on pull request events
on:
  pull_request:
    branches:
      - main  # Runs when a pull request targets the main branch
  push:
    branches:
      - main  # Runs when code is pushed to the main branch (e.g., after merging a PR)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Matches the engine requirement from package.json
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build -w @letrun/core && npm run build -w @letrun/plugin npm run build -w @letrun/task && npm run build -w @letrun/cli

      - name: Run tests
        run: npm run test
